"""Codex agent runner — spawns `codex exec` (OpenAI Codex CLI) as the
agent, mirroring `claude_runner.run`'s contract so `runner.run` can dispatch
on the model name (`is_codex_model`) and keep one downstream pipeline.

Parity with the Claude agent (and the deliberate gaps):

- Auth: `OPENAI_API_KEY` from the global testbed `.env` (loaded into the env by
  the CLI), or a host `~/.codex/auth.json` (from `codex login`) copied into the
  run's redirected CODEX_HOME.
- Isolation: CODEX_HOME → `<run>/.codex` so config/sessions land inside the run
  dir; codex's own OS sandbox (`workspace-write`) confines writes to the run
  dir, with network enabled for platform calls.
- MCP: the interface's `mcp_servers` are written to CODEX_HOME/config.toml.
- ENFORCEMENT GAP: codex has no PreToolUse-hook equivalent, so the remote-only /
  single-interface allowlist is NOT enforced in-flight for codex agents.
  Off-interface and local-python use remains fully VISIBLE post-hoc (the
  accounting below), it just isn't blocked. Compare codex-agent rows with
  that in mind.
- Accounting: raw `codex exec --json` events land in `codex_events.jsonl` and
  are NORMALIZED into a Claude-style stream-json `transcript.jsonl` (assistant
  `tool_use` blocks + a final `result` event with usage/num_turns), so
  `results.parse_transcript_usage` / `aggregate_commands` / `write_commands_log`
  work unchanged on codex runs.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

from mlpab.claude_runner import ClaudeResult


def is_codex_model(model: str) -> bool:
    """Route a model name to the codex engine: OpenAI model ids (`gpt-*`) and
    anything explicitly codex-flavoured (`gpt-5.1-codex`, `codex-mini`, …)."""
    m = (model or "").lower()
    return "codex" in m or m.startswith("gpt-")


def _toml_str(s: str) -> str:
    # json string escaping is valid TOML basic-string escaping.
    return json.dumps(s)


def _write_codex_config(
    codex_home: Path,
    mcp_servers: dict[str, Any],
    run_dir: Path,
) -> Path:
    """CODEX_HOME/config.toml: MCP servers + sandbox with network access.

    `workspace-write` confines writes to cwd (the run dir). Network stays ON —
    the whole point is remote platform calls.
    """
    lines: list[str] = [
        "# Generated by mlpab codex_runner — per-run codex config.",
        "sandbox_mode = \"workspace-write\"",
        "",
        "[sandbox_workspace_write]",
        "network_access = true",
        f"writable_roots = [{_toml_str(str(run_dir.resolve()))}]",
    ]
    for name, server in (mcp_servers or {}).items():
        lines += ["", f"[mcp_servers.{name}]"]
        lines.append(f"command = {_toml_str(server.get('command', ''))}")
        # Slow-starting stdio servers (databricks UC: ~20s of imports before
        # tool enumeration) die under codex's 10s default startup timeout, and
        # remote-job tool calls outlive the 60s default tool timeout.
        lines.append("startup_timeout_sec = 180")
        lines.append("tool_timeout_sec = 3600")
        args = server.get("args") or []
        lines.append("args = [" + ", ".join(_toml_str(str(a)) for a in args) + "]")
        env = server.get("env") or {}
        if env:
            kv = ", ".join(f"{k} = {_toml_str(str(v))}" for k, v in env.items())
            lines.append(f"env = {{ {kv} }}")
    codex_home.mkdir(parents=True, exist_ok=True)
    cfg = codex_home / "config.toml"
    cfg.write_text("\n".join(lines) + "\n")
    return cfg


# codex --json item types → Claude-style tool_use blocks. Unknown types fall
# through to None (not a tool call; e.g. agent_message/reasoning/todo_list).
def _item_to_tool_use(item: dict[str, Any]) -> dict[str, Any] | None:
    itype = item.get("item_type") or item.get("type")
    if itype == "command_execution":
        return {"type": "tool_use", "name": "Bash",
                "input": {"command": item.get("command") or ""}}
    if itype == "mcp_tool_call":
        server = item.get("server") or "server"
        tool = item.get("tool") or "tool"
        return {"type": "tool_use", "name": f"mcp__{server}__{tool}",
                "input": item.get("arguments") or {}}
    if itype == "file_change":
        # Buckets as edit_calls — codex edits files via its own tool, not
        # Bash; the exact path list isn't needed for accounting.
        return {"type": "tool_use", "name": "Edit", "input": {}}
    if itype == "web_search":
        return {"type": "tool_use", "name": "WebSearch",
                "input": {"query": item.get("query") or ""}}
    return None


def normalize_events(raw_path: Path, transcript_path: Path) -> None:
    """Rewrite raw `codex exec --json` events as a Claude-style stream-json
    transcript: one `assistant` event per tool call, one final `result` event
    with summed usage + turn count."""
    input_tokens = output_tokens = num_turns = 0
    session_id: str | None = None
    out_lines: list[str] = []
    if raw_path.exists():
        for line in raw_path.read_text().splitlines():
            if not line.strip():
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue
            etype = event.get("type")
            if etype == "thread.started":
                session_id = event.get("thread_id")
                continue
            if etype == "turn.completed":
                usage = event.get("usage") or {}
                input_tokens += int(usage.get("input_tokens") or 0)
                output_tokens += int(usage.get("output_tokens") or 0)
                num_turns += 1
                continue
            if etype == "item.completed":
                item = event.get("item") or {}
                block = _item_to_tool_use(item)
                if block:
                    out_lines.append(json.dumps({
                        "type": "assistant",
                        "session_id": session_id,
                        "timestamp": event.get("timestamp"),
                        "message": {"content": [block]},
                    }))
                    # A failed command surfaces as an errored tool_result, so
                    # `failed_commands` counts codex rows too. (No hook for
                    # codex → denied_calls stays 0 by construction.)
                    exit_code = item.get("exit_code")
                    if block["name"] == "Bash" and exit_code not in (None, 0):
                        out_lines.append(json.dumps({
                            "type": "user",
                            "session_id": session_id,
                            "message": {"content": [{
                                "type": "tool_result", "is_error": True,
                                "content": f"exit {exit_code}",
                            }]},
                        }))
    out_lines.append(json.dumps({
        "type": "result",
        "session_id": session_id,
        "usage": {"input_tokens": input_tokens, "output_tokens": output_tokens},
        "num_turns": num_turns,
        # codex --json carries no cost; cost_usd stays 0 for codex rows.
        "total_cost_usd": 0.0,
    }))
    transcript_path.write_text("\n".join(out_lines) + "\n")


def _print_event(line: str) -> None:
    """Compact per-event progress line (lands in agent.log via the tee)."""
    try:
        event = json.loads(line)
    except json.JSONDecodeError:
        return
    etype = event.get("type")
    if etype == "item.completed":
        item = event.get("item") or {}
        itype = item.get("item_type") or item.get("type")
        if itype == "command_execution":
            print(f"[agent:codex] $ {(item.get('command') or '')[:200]}", flush=True)
        elif itype == "mcp_tool_call":
            print(f"[agent:codex] mcp {item.get('server')}.{item.get('tool')}", flush=True)
        elif itype == "agent_message":
            text = (item.get("text") or "").strip().replace("\n", " ")
            if text:
                print(f"[agent:codex] {text[:300]}", flush=True)
    elif etype == "turn.completed":
        usage = event.get("usage") or {}
        print(f"[agent:codex] turn done (in={usage.get('input_tokens')}, "
              f"out={usage.get('output_tokens')})", flush=True)
    elif etype == "error":
        print(f"[agent:codex] ERROR: {event.get('message')}", flush=True)


def run(
    prompt: str,
    run_dir: Path,
    auth: str,
    model: str,
    cli_binary: str | None,
    sdk_module: str | None,
    mcp_servers: dict[str, Any],
    command_log: Path,
    cli_subcommand: str | None = None,
    timeout_s: int | None = 60 * 60,   # None → NO wall-clock cap
    extra_env: dict[str, str] | None = None,
    allowed_domains: list[str] | None = None,
    interface: str | None = None,
    compute_deny: list[str] | None = None,
    instance_allowlist: list[str] | None = None,
    sandbox_excluded_commands: list[str] | None = None,
    platform: str | None = None,
) -> ClaudeResult:
    """Spawn `codex exec` (the agent). Same contract as `claude_runner.run`;
    hook-only parameters (cli_binary/sdk_module/interface/compute_deny/
    allowed_domains/instance_allowlist/sandbox_excluded_commands/platform) are
    accepted for signature parity but unenforceable here — see the module
    docstring's ENFORCEMENT GAP note."""
    if shutil.which("codex") is None:
        raise RuntimeError("`codex` CLI not found on PATH. Run `make install` "
                           "(installs @openai/codex) or `npm i -g @openai/codex`.")

    codex_home = run_dir / ".codex"
    _write_codex_config(codex_home, mcp_servers, run_dir)

    env = os.environ.copy()
    env["CODEX_HOME"] = str(codex_home)
    if not env.get("OPENAI_API_KEY"):
        # No API key — fall back to the host's `codex login` session, copied into
        # the redirected CODEX_HOME so host state is never mutated.
        host_auth = Path.home() / ".codex" / "auth.json"
        if host_auth.exists():
            shutil.copy(host_auth, codex_home / "auth.json")
            os.chmod(codex_home / "auth.json", 0o600)
        else:
            print("[mlpab] WARNING: no OPENAI_API_KEY in env/.env and no "
                  "~/.codex/auth.json — codex agent will fail to authenticate.",
                  flush=True)
    if extra_env:
        env.update({k: v for k, v in extra_env.items() if v})

    raw_path = run_dir / "codex_events.jsonl"
    transcript_path = run_dir / "transcript.jsonl"
    stderr_path = run_dir / "codex.stderr.log"
    command_log.touch()  # codex has no PreToolUse hook to append; runner rebuilds
    # commands.jsonl from the normalized transcript afterwards.

    cmd = [
        "codex", "exec",
        "--json",
        "--model", model,
        "--cd", str(run_dir),
        "--skip-git-repo-check",
        prompt,
    ]

    start = time.monotonic()
    with open(raw_path, "w") as raw_f, open(stderr_path, "w") as err_f:
        proc = subprocess.Popen(
            cmd, cwd=run_dir, env=env,
            stdout=subprocess.PIPE, stderr=err_f, text=True,
        )
        # Hard wall-clock cap (when set): a stalled command emits no output, so a
        # read loop alone can block past the deadline — the timer kills the
        # process. timeout_s=None → uncapped, no timer.
        timer = threading.Timer(timeout_s, proc.kill) if timeout_s is not None else None
        if timer is not None:
            timer.start()
        try:
            for line in proc.stdout:  # type: ignore[union-attr]
                raw_f.write(line)
                raw_f.flush()
                _print_event(line.rstrip("\n"))
            exit_code = proc.wait()
        finally:
            if timer is not None:
                timer.cancel()
    wall = time.monotonic() - start
    if timeout_s is not None and wall >= timeout_s:
        print(f"[mlpab] codex agent hit the {timeout_s}s wall-clock cap and "
              f"was killed.", flush=True)

    normalize_events(raw_path, transcript_path)

    if stderr_path.exists() and stderr_path.stat().st_size == 0:
        stderr_path.unlink()

    # tool_spans stays empty: codex raw events aren't span-timed yet, so a
    # codex row reports platform_time_s=0 and local_time_s=wall — treat the
    # split as UNKNOWN for codex runs until the normalizer stamps arrival
    # times the way claude_runner.ToolTimer does.
    return ClaudeResult(
        exit_code=exit_code,
        wall_time_s=wall,
        transcript_path=transcript_path,
        stderr_path=stderr_path,
    )


def engine_ready() -> tuple[bool, str]:
    """Is the Codex agent engine usable? (`codex` on PATH + OPENAI_API_KEY or login.)"""
    import shutil
    from pathlib import Path as _P
    if shutil.which("codex") is None:
        return False, "`codex` CLI not on PATH — `npm i -g @openai/codex` (make install)"
    ok = bool(os.environ.get("OPENAI_API_KEY")) or (_P.home() / ".codex" / "auth.json").exists()
    return ok, "OPENAI_API_KEY or ~/.codex/auth.json present" if ok else \
        "no OPENAI_API_KEY and no ~/.codex/auth.json (run `codex login`)"
