"""Mistral agent runner — spawns `vibe` (Mistral Vibe CLI, powered by Devstral)
as the agent, mirroring `claude_runner.run`'s contract so `runner.run` can
dispatch on the model name (`is_mistral_model`) and keep one downstream pipeline.

Vibe is a terminal coding agent. Headless invocation:

    vibe --prompt "<task>" --model <id> --output streaming --workdir <run_dir> --trust

`--prompt` runs one prompt to completion auto-approving tools (no TUI); `--output
streaming` emits newline-delimited JSON per message; `--trust` trusts the
working dir for this invocation.

Parity with the Claude agent (and the deliberate gaps):

- Auth: `MISTRAL_API_KEY` from the global testbed `.env` (loaded into the env by
  the CLI). No login-session fallback.
- Isolation: VIBE_HOME → `<run>/.vibe` so vibe's config.toml and session logs
  land inside the run dir (vibe reads its config from VIBE_HOME, not XDG);
  `--workdir <run_dir>` + `--trust` confine it to the run.
- Enforcement: vibe has no PreToolUse-hook equivalent, but it runs every command
  via `create_subprocess_shell(cmd, executable=$SHELL)`, so claude_runner's
  `install_exec_gate` points $SHELL at the exec gate (hooks/exec_gate.py) that
  runs the SAME `enforce()` as the Claude hook before each command. The
  single-interface allowlist is thus enforced IN-FLIGHT, at parity with Claude.
- Accounting: raw `--output streaming` events land in `vibe_events.jsonl` and
  are NORMALIZED into a Claude-style `transcript.jsonl` so
  `results.parse_transcript_usage` / `aggregate_commands` work unchanged.

⚠ LIVE-PROBE REQUIRED: vibe's streaming-event schema (the per-message `type`
names) is PROVISIONAL here — run `vibe --prompt … --output streaming` once and
refine `_event_to_tool_use` / `normalize_events` against the real events (same
as codex_runner needed). Token usage was confirmed from a live run: it lives in
`meta.json` under `stats.session_{prompt,completion}_tokens` (see
`_session_tokens`); cost is left 0 and filled by `results.usd_cost` (litellm).
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

from mlpab import streaming
from mlpab.claude_runner import (
    ClaudeResult,
    activate_run_venv,
    install_exec_gate,
    run_streaming_with_backoff,
    set_enforcement_env,
    streaming_is_rate_limited,
    text_is_transient_error,
)

# Testbed model id (alias, used in configs + `--model`) → Mistral API id (what
# vibe sends). EDITABLE — point at version-pinned API ids instead of `-latest`
# if you need to pin (e.g. Mistral Medium 3.5 / Small 4 / Large 3 exact builds).
MODEL_API = {
    "mistral-medium-3.5": "mistral-medium-latest",
    "mistral-small-4": "mistral-small-latest",
    "mistral-large-3": "mistral-large-latest",
}
MODEL_IDS = tuple(MODEL_API)
TEMPERATURE = 0.2


def is_mistral_model(model: str) -> bool:
    """Route a model name to the Mistral Vibe engine: Mistral model ids
    (`mistral-*`)."""
    m = (model or "").lower()
    return m.startswith("mistral-") or "mistral" in m


def _write_vibe_config(vibe_home: Path, model: str) -> None:
    """Write a SELF-CONTAINED vibe config to VIBE_HOME/config.toml (vibe reads its
    config from VIBE_HOME, NOT XDG). Defines the `mistral` provider (Mistral API,
    key from MISTRAL_API_KEY) + every supported model as a `[[models]]` entry
    (name = real Mistral API id, alias = testbed id) and selects the requested one
    via top-level `active_model`. Top-level keys precede the `[[…]]` tables (TOML
    binds bare keys to the most recent table otherwise)."""
    vibe_home.mkdir(parents=True, exist_ok=True)
    aliases = dict(MODEL_API)
    aliases.setdefault(model, model)  # unknown id → use it verbatim as its own API id
    lines = [
        "# Generated by mlpab mistral_runner — per-run vibe config (VIBE_HOME).",
        f"active_model = {json.dumps(model)}",
        'default_agent = "default"',
        "mcp_servers = []",
        "",
        "[[providers]]",
        'name = "mistral"',
        'api_base = "https://api.mistral.ai/v1"',
        'api_key_env_var = "MISTRAL_API_KEY"',
        'api_style = "openai"',
        'backend = "mistral"',
        "",
    ]
    for alias, api in aliases.items():
        lines += [
            "[[models]]",
            f"name = {json.dumps(api)}",
            'provider = "mistral"',
            f"alias = {json.dumps(alias)}",
            f"temperature = {TEMPERATURE}",
            "",
        ]
    (vibe_home / "config.toml").write_text("\n".join(lines) + "\n")


# vibe tool name → Claude-style name (for command/edit/read accounting buckets).
_VIBE_TOOL = {
    "bash": "Bash",
    "edit": "Edit",
    "write_file": "Write",
    "read": "Read",
    "grep": "Grep",
    "web_search": "WebSearch",
    "web_fetch": "WebFetch",
}


def _tool_use_block(name: str, args: dict[str, Any]) -> dict[str, Any]:
    claude = _VIBE_TOOL.get(name, name)
    inp = {"command": args.get("command", "")} if claude == "Bash" else (args or {})
    return {"type": "tool_use", "name": claude, "input": inp}


def _session_tokens(run_dir: Path) -> tuple[int, int]:
    """Total (prompt, completion) tokens from vibe's session meta.json (vibe does
    NOT put usage in the streamed messages; it writes it to the session log)."""
    metas = sorted((run_dir / ".vibe" / "logs" / "session").glob("*/meta.json"))
    if not metas:
        return 0, 0
    try:
        m = json.loads(metas[-1].read_text())
        # vibe writes usage under a `stats` object; fall back to the top level
        # in case the schema flattens it in a future version.
        stats = m.get("stats") if isinstance(m.get("stats"), dict) else m
        return int(stats.get("session_prompt_tokens") or 0), int(
            stats.get("session_completion_tokens") or 0
        )
    except Exception:
        return 0, 0


def normalize_events(raw_path: Path, transcript_path: Path) -> None:
    """Rewrite vibe's `--output streaming` messages (role assistant/tool/user) as
    a Claude-style transcript: an `assistant` tool_use per tool call, a `tool`
    result (is_error on failures), and a final `result` event. Tokens come from
    the session meta.json (vibe doesn't stream usage); cost is left 0 here and
    filled by `results.usd_cost` (litellm) from those tokens."""
    num_turns = 0
    out_lines: list[str] = []
    if raw_path.exists():
        for line in raw_path.read_text().splitlines():
            if not line.strip():
                continue
            try:
                msg = json.loads(line)
            except json.JSONDecodeError:
                continue
            role = msg.get("role")
            if role == "assistant":
                num_turns += 1
                for tc in msg.get("tool_calls") or []:
                    fn = tc.get("function") or tc
                    name = fn.get("name") or tc.get("name") or "tool"
                    raw_args = fn.get("arguments")
                    try:
                        args = (
                            json.loads(raw_args) if isinstance(raw_args, str) else (raw_args or {})
                        )
                    except (json.JSONDecodeError, TypeError):
                        args = {}
                    out_lines.append(
                        json.dumps(
                            {
                                "type": "assistant",
                                "message": {"content": [_tool_use_block(name, args)]},
                            }
                        )
                    )
            elif role == "tool":
                content = str(msg.get("content") or "")
                # Trust only an explicit error signal from vibe — a successful
                # result whose text merely starts with "error" (reading a file
                # about error handling, an echoed log line) must not be counted
                # as a failed command.
                is_err = (
                    bool(msg.get("is_error")) or str(msg.get("status") or "").lower() == "error"
                )
                out_lines.append(
                    json.dumps(
                        {
                            "type": "user",
                            "message": {
                                "content": [
                                    {
                                        "type": "tool_result",
                                        "is_error": is_err,
                                        "content": content[:200],
                                    }
                                ]
                            },
                        }
                    )
                )
    in_tok, out_tok = _session_tokens(raw_path.parent)
    out_lines.append(
        json.dumps(
            {
                "type": "result",
                "usage": {"input_tokens": in_tok, "output_tokens": out_tok},
                "num_turns": num_turns,
                "total_cost_usd": 0.0,
            }
        )
    )
    transcript_path.write_text("\n".join(out_lines) + "\n")


def _print_event(line: str) -> None:
    """Render a vibe `--output streaming` event as Claude-style `[agent:…]` lines
    (the SAME formatter as claude_runner — streaming.assistant_lines /
    tool_result_lines), so the mistral run's live pane and agent.log match the
    Claude runner's. vibe's schema (NOT claude stream-json): role=="assistant"
    carries free-text `content` and/or `tool_calls` (function.arguments is a
    JSON STRING); role=="tool" carries a `content` string result; errors arrive
    as type/role=="error"."""
    try:
        event = json.loads(line)
    except json.JSONDecodeError:
        return
    role = (event.get("role") or "").lower()
    if (event.get("type") or "").lower() == "error" or role == "error":
        msg = str(event.get("message") or event.get("content") or "") or json.dumps(event)[:200]
        for ln in msg.splitlines() or [""]:
            print(f"[agent:result-err] {ln}", flush=True)
        return
    if role == "assistant":
        text = event.get("content")
        if isinstance(text, str):
            for ln in text.splitlines():
                if ln.strip():
                    print(f"[agent] {ln}", flush=True)
        reasoning = event.get("reasoning_content")
        if isinstance(reasoning, str) and reasoning.strip():
            for ln in reasoning.splitlines():
                if ln.strip():
                    print(f"[agent:thinking] {ln}", flush=True)
        for tc in event.get("tool_calls") or []:
            fn = tc.get("function") or tc
            name = fn.get("name") or tc.get("name") or "tool"
            raw_args = fn.get("arguments")
            try:
                args = json.loads(raw_args) if isinstance(raw_args, str) else (raw_args or {})
            except (json.JSONDecodeError, TypeError):
                args = {}
            ev = {"type": "assistant", "message": {"content": [_tool_use_block(name, args)]}}
            for ln in streaming.assistant_lines(ev, "agent"):
                print(ln, flush=True)
    elif role == "tool":
        is_err = bool(event.get("is_error")) or str(event.get("status") or "").lower() == "error"
        ev = {
            "type": "user",
            "message": {
                "content": [
                    {
                        "type": "tool_result",
                        "is_error": is_err,
                        # Cap so a chatty command can't flood the pane/agent.log;
                        # full body stays in vibe_events.jsonl.
                        "content": streaming.cap_for_live(str(event.get("content") or "")),
                    }
                ]
            },
        }
        for ln in streaming.tool_result_lines(ev, "agent"):
            print(ln, flush=True)


# Transport-layer blips between vibe and the Mistral API: vibe's httpx client
# drops the request socket mid-run (an httpx `ReadError`/`ConnectError`, a read
# timeout), surfaced as `LLM backend error [mistral] … provider_message: Network
# error` on stderr. These are the vibe analogue of claude_runner's Node-transport
# `_DISCONNECT_PHRASES`: an instantaneous network fault that clears on retry, NOT
# a rate limit or 5xx. They live HERE (vibe-scoped), not in the global
# `_TRANSIENT_PHRASES`, because vibe surfaces them only on its transport layer —
# folding them into the shared predicate would let a tool result echoing
# "network error" trip a false retry in the Claude/codex paths.
_VIBE_TRANSPORT_PHRASES = (
    "network error",
    "readerror",
    "read error",
    "connecterror",
    "connect error",
    "connection error",
    "read timeout",
    "readtimeout",
    "connection reset",
    "remoteprotocolerror",
)


def _vibe_text_is_retryable(text: str) -> bool:
    """Retry on a rate-limit / transient-5xx condition (shared predicate) OR on a
    vibe↔Mistral transport disconnect (`_VIBE_TRANSPORT_PHRASES`)."""
    t = (text or "").lower()
    return text_is_transient_error(t) or any(p in t for p in _VIBE_TRANSPORT_PHRASES)


def _rate_limited(raw_path: Path, stderr_path: Path) -> bool:
    """A vibe run failed on a rate-limit / transient-server / transport-disconnect
    condition worth retrying. vibe surfaces errors as
    `{"type":"error","message":...}` (or a role=="error" message) and on stderr."""

    def _err_text(msg: dict) -> str:
        if (msg.get("type") or "").lower() == "error" or (msg.get("role") or "").lower() == "error":
            return str(msg.get("message") or msg.get("content") or "")
        return ""

    return streaming_is_rate_limited(
        raw_path, stderr_path, _err_text, text_is_retryable=_vibe_text_is_retryable
    )


def run(
    prompt: str,
    run_dir: Path,
    auth: str,
    model: str,
    cli_binary: str | None,
    sdk_module: str | None,
    mcp_servers: dict[str, Any],
    command_log: Path,
    cli_subcommand: str | None = None,
    cli_aux_commands: list[str] | None = None,
    timeout_s: int | None = 60 * 60,
    extra_env: dict[str, str] | None = None,
    allowed_domains: list[str] | None = None,
    interface: str | None = None,
    compute_deny: list[str] | None = None,
    instance_allowlist: list[str] | None = None,
    sandbox_excluded_commands: list[str] | None = None,
    platform: str | None = None,
) -> ClaudeResult:
    """Spawn `vibe --prompt` (the agent). Same contract as `claude_runner.run`;
    hook-only parameters are accepted for signature parity but unenforceable here
    (see the module docstring's ENFORCEMENT GAP note)."""
    if shutil.which("vibe") is None:
        raise RuntimeError(
            "`vibe` CLI not found on PATH. Run `make install` "
            "(installs mistral-vibe) or `uv tool install mistral-vibe`."
        )

    run_dir = Path(run_dir).absolute()
    vibe_home = run_dir / ".vibe"
    _write_vibe_config(vibe_home, model)

    env = os.environ.copy()
    env["VIBE_HOME"] = str(vibe_home)  # vibe reads config.toml from VIBE_HOME
    if not env.get("MISTRAL_API_KEY"):
        print(
            "[mlpab] WARNING: no MISTRAL_API_KEY in env/.env — the mistral "
            "(vibe) agent will fail to authenticate.",
            flush=True,
        )
    if extra_env:
        env.update({k: v for k, v in extra_env.items() if v})

    # Activate the per-run venv so the agent's bash finds the interface binary
    # (e.g. the `aws` / `databricks` console script) and its python/pip see the
    # interface + ML deps. vibe inherits this env, so without it every CLI-mode
    # call dies with `command not found` (rc 127).
    activate_run_venv(env, run_dir)

    # In-flight single-interface enforcement (parity with the Claude hook). vibe
    # runs every command via `create_subprocess_shell(cmd, executable=$SHELL)`,
    # so set_enforcement_env populates the TESTBED_* allowlist and install_exec_gate
    # points $SHELL at the gate that runs `enforce()` before each command.
    set_enforcement_env(
        env,
        run_dir=run_dir,
        command_log=command_log,
        interface=interface,
        cli_binary=cli_binary,
        cli_subcommand=cli_subcommand,
        cli_aux_commands=cli_aux_commands,
        sdk_module=sdk_module,
        compute_deny=compute_deny,
        instance_allowlist=instance_allowlist,
        platform=platform,
    )
    install_exec_gate(run_dir, env)

    raw_path = run_dir / "vibe_events.jsonl"
    transcript_path = run_dir / "transcript.jsonl"
    stderr_path = run_dir / "vibe.stderr.log"
    command_log.touch()  # no PreToolUse hook; commands.jsonl rebuilt from transcript

    # vibe selects the model from config.toml `active_model` (written above), NOT
    # a flag; -p is programmatic mode, --auto-approve allows tool calls headlessly.
    cmd = [
        "vibe",
        "--prompt",
        prompt,
        "--output",
        "streaming",
        "--workdir",
        str(run_dir),
        "--trust",
        "--auto-approve",
    ]

    # Same accounting as the Claude agent: exponential rate-limit back-off and a
    # cumulative COMPUTE deadline. `wall` includes any back-off sleep; `rl_wait`
    # is the slept portion, so the row's compute time = wall − rl_wait.
    exit_code, wall, rl_wait = run_streaming_with_backoff(
        cmd,
        run_dir,
        env,
        raw_path,
        stderr_path,
        is_rate_limited=_rate_limited,
        timeout_s=timeout_s,
        on_line=_print_event,
        log_prefix="mlpab:mistral",
    )
    if rl_wait:
        print(
            f"[mlpab] mistral rate-limit waits excluded from wall time: {rl_wait:.0f}s", flush=True
        )
    if exit_code == 124:
        print(
            f"[mlpab] mistral (vibe) agent hit the {timeout_s}s compute budget and was killed.",
            flush=True,
        )

    normalize_events(raw_path, transcript_path)
    if stderr_path.exists() and stderr_path.stat().st_size == 0:
        stderr_path.unlink()

    # tool_spans empty (raw events aren't span-timed) → platform_time_s=0,
    # local_time_s=wall; treat the split as UNKNOWN for mistral runs, like codex.
    return ClaudeResult(
        exit_code=exit_code,
        wall_time_s=wall,
        transcript_path=transcript_path,
        stderr_path=stderr_path,
        rate_limit_wait_s=rl_wait,
    )


def engine_ready() -> tuple[bool, str]:
    """Is the Mistral Vibe agent engine usable? (`vibe` on PATH + MISTRAL_API_KEY.)"""
    import shutil

    if shutil.which("vibe") is None:
        return False, "`vibe` CLI not on PATH — `uv tool install mistral-vibe` (make install)"
    ok = bool(os.environ.get("MISTRAL_API_KEY"))
    return ok, "MISTRAL_API_KEY set" if ok else "MISTRAL_API_KEY MISSING"


def engine_live(model: str, auth: str | None = None, timeout_s: int = 60) -> tuple[bool, str]:
    """Live responsiveness probe: send a one-word prompt to `model` via
    `vibe --prompt` and confirm it answers. Returns (ok, detail). Uses a
    throwaway VIBE_HOME so it touches no testbed state."""
    import shutil
    import tempfile

    ready, detail = engine_ready()
    if not ready:
        return False, detail
    tmp = Path(tempfile.mkdtemp(prefix="mlpab-llmprobe-"))
    try:
        vibe_home = tmp / ".vibe"
        _write_vibe_config(vibe_home, model)  # vibe picks the model from here
        env = os.environ.copy()
        env["VIBE_HOME"] = str(vibe_home)
        cmd = [
            "vibe",
            "--prompt",
            "Reply with the single word: READY",
            "--output",
            "streaming",
            "--workdir",
            str(tmp),
            "--trust",
            "--auto-approve",
        ]
        try:
            proc = subprocess.run(
                cmd,
                cwd=str(tmp),
                env=env,
                stdin=subprocess.DEVNULL,
                capture_output=True,
                text=True,
                timeout=timeout_s,
            )
        except subprocess.TimeoutExpired:
            return False, f"no response within {timeout_s}s"
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    if proc.returncode == 0:
        return True, f"responded ({model})"
    tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-2:]
    return False, f"exit {proc.returncode}: {' / '.join(tail)[:200]}"
